version: "3"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: user_test
            POSTGRES_DB: test
        ports:
        - '5432:5432'
        volumes: 
        - ./postgres-data:/var/lib/postgresql/data 
